name: Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar Dependencias
        run: poetry install

      - name: Conceder permissão de execução ao serviço
        run: chmod +x ./app.py

      - name: Visualizar Pastas
        run: echo $(ls)

      - name: Rodar Aplicação
        run: poetry run pytest

      - name: Login no github container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build da imagem
        run: docker build -t ghcr.io/amarildozoletjunior/tccprivado:"$(cat docker-settings.json | jq -r .version)" .