name: Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar Dependencias
        run: poetry install

      - name: Conceder permissão de execução ao serviço
        run: chmod +x ./app.py

      - name: Visualizar Pastas
        run: echo $(ls)

      - name: Rodar Aplicação
        run: poetry run pytest

      # - name: Login no github container registry
      #   run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # - name: Build da imagem
      #   run: docker build -t ghcr.io/amarildozoletjunior/tccprivado:"$(cat docker-settings.json | jq -r .version)" .

      # - name: Enviando imagem ao repositório
      #   run: docker push ghcr.io/amarildozoletjunior/tccprivado:"$(cat docker-settings.json | jq -r .version)"

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # - name: Build da imagem
      #   run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tccprivado:"$(cat docker-settings.json | jq -r .version)" .

      # - name: Enviando imagem ao Docker Hub
      #   run: docker push ${{ secrets.DOCKER_USERNAME }}/tccprivado:"$(cat docker-settings.json | jq -r .version)"

